#!/usr/bin/env ruby
require "gtk3"
require_relative "./reader"

builder      = Gtk::Builder.new
builder_file = File.dirname(File.expand_path(__FILE__)) + '/gui.ui'
builder.add_from_file builder_file

window = builder.get_object 'window1'
window.signal_connect 'destroy' do
  Gtk.main_quit
end

['button1', 'button2'].each do |button_name|
  button = builder.get_object button_name
  button.signal_connect 'clicked' do
    puts button_name
  end
end

list = builder.get_object 'listbox1'
reader = HNReader.new

reader.top_ids[0..10].each_with_index do |id, i|
  Thread.new do
    story  = reader.request id
    button = Gtk::LinkButton.new story['url'], story['title']
    list.add button
    window.show_all
  end
end

Gtk.main
