#!/usr/bin/env ruby
# gem 'gtk3'
require "gtk3"
require_relative "./reader"

builder_file = File.dirname(File.expand_path(__FILE__)) + '/gui.ui'

builder = Gtk::Builder.new
builder.add_from_file builder_file

window = builder.get_object 'window1'
window.signal_connect 'destroy' do
  Gtk.main_quit
end

button = builder.get_object 'button1'
button.signal_connect 'clicked' do
  puts 'button 1'
end

button = builder.get_object 'button2'
button.signal_connect 'clicked' do
  puts 'button 2'
end

list = builder.get_object 'listbox1'
reader = HNReader.new
reader.top_ids.each do |id|
  Thread.new do
    story = reader.request id
    button = Gtk::LinkButton.new story['url'], story['title']
    list.add button
    window.show_all
  end
end

window.show_all
Gtk.main
